### ISSUE TITLE
Escrow

### ISSUE THREAD

**Issue by sanchez** [draganmarjanovic/DBNB#2]
Fucking finish this already

**Comment by jeevan-shikaram** [comment]
Sorry mate no swearing marius has access to this

**Comment by jeevan-shikaram** [comment]
The escrow contract assumes values are in Wei, and as such we will need to change all of the back end to be in Wei.

The front end will then need to convert Wei into a suitable value, either ETH or mETH

**Comment by sanchez** [comment]
Not an automated system, but still implemented and can be demoed
