### ISSUE TITLE
Fix issues with BookingManager

### ISSUE THREAD

**Issue by sanchez** [draganmarjanovic/DBNB#3]
Fix the error with BookingManager and VM Exceptions

**Comment by abhijagtap** [comment]
How do I reproduce the bug?

**Comment by sanchez** [comment]
Home.js on line 103. There is a bunch of commented code
If you uncomment this and open the console on browser. The booking will fail

**Comment by abhijagtap** [comment]
Just opening the browser will show me the error? Or is there any process, eg:- making a listing and an account, etc

**Comment by sanchez** [comment]
Deemed too much of a timesink and as a result has been abandoned
